blog/urls.py
from django.urls import path

from . import views

# pozwala na organizacje urli na aplikacje

app_name = "blog"

urlpatterns = [
    # name gdy wykorzystujemy np reverse
    path("list", views.post_list, name="post_list"),
    # path converters https://docs.djangoproject.com/en/2.0/topics/http/urls/#path-converters.
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("", views.PostListView.as_view(), name="post_list_cls"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("my-posts/", views.MyPostListView.as_view(), name="my_posts"),
    path("add/", views.PostCreateView.as_view(), name="post_add"),
    path("<int:pk>/edit/", views.PostUpdateView.as_view(), name="post_edit"),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="post_delete"),
]

blogapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # regex do path  https://docs.python.org/3/howto/regex.html
    path("admin/", admin.site.urls),
    # include bo ladujesz urle z aplikacji
    # namespace po to zeby odnosic sie do url blogow z mojej aplikacji np blog:post_details
    # https://docs.djangoproject.com/en/2.0/topics/http/urls/#url-namespaces.
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone

from blogapp import settings


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return (
            super(PublishedPostManager, self).get_queryset().filter(status="published")
        )


class Post(models.Model):
    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"))
    title = models.TextField(max_length=255)
    slug = models.SlugField(max_length=256, unique_for_date="publish")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    image = models.ImageField(upload_to="post_images/", blank=True, null=True)

    objects = models.Manager()
    published = PublishedPostManager()

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

blog/forms.py
from django import forms

from blog.models import Comment, Post


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "body", "status", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.template.context_processors import request
from django.template.loader import render_to_string
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from blog.forms import CommentForm, EmailPostForm, PostForm
from blog.models import Post
from users.models import Company

# https://docs.djangoproject.com/en/2.0/topics/class-based-views/intro/.


class PostListView(ListView):
    # can use model = Post and default manager will be used
    queryset = Post.published.all()
    # default list object_list
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"

    def get_queryset(self):
        site = get_current_site(self.request)
        tenant = get_object_or_404(Company, site=site)
        ## to sie rowna to samo co request.tenant dzieki middleware
        tenant = getattr(self.request, "tenant", None)
        return super().get_queryset().filter(author__company=tenant)


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html", {"posts": posts, "page": page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == "POST":
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.post = post
                new_comment.author = request.user
                new_comment.save()
                return redirect(request.path_info)
        else:
            return redirect("login")
    else:
        form = CommentForm()

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "new_comment": new_comment,
        },
    )


def post_share(request, post_id):
    sent = False
    post = get_object_or_404(Post, id=post_id, status="published")
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # budowanie url absolutnego
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']}) recommends you reading {post.title}"
            )
            message = f"Read {post.title} at {post_url}\n\n{cd['name']} comments: {cd['comments']}"

            message = render_to_string(
                "blog/post/share_email.txt",
                {
                    "post": post,
                    "post_url": post_url,
                    "name": cd["name"],
                    "email": cd["email"],
                    "comments": cd["comments"],
                },
            )

            send_mail(subject, message, "admin@myblog.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


class MyPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "blog/post/my_posts.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post/post_form.html"
    success_url = reverse_lazy("blog:my_posts")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "blog/post/post_form.html"
    success_url = reverse_lazy("blog:my_posts")

    def test_func(self):
        return self.get_object().author == self.request.user


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "blog/post/post_confirm_delete.html"
    success_url = reverse_lazy("blog:my_posts")

    def test_func(self):
        return self.get_object().author == self.request.user

templates/blog/post/detail.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    {% if post.image %}
        <div>
            <img src="{{ post.image.url }}" class="image" alt="{{ post.title }}">
        </div>
    {% endif %}
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body | linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    <h2>Comments</h2>
    {% for comment in comments %}
        <div>
            <strong>{{ comment.author }}</strong> - {{ comment.created }}
            <p>{{ comment.body }}</p>
        </div>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}

    {% if user.is_authenticated %}
        <h3>Leave a comment</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% else %}
        <p><a href="{% url 'login' %}">Log in</a> to leave a comment.</p>
    {% endif %}
{% endblock %}

templates/blog/post/list.html
{% extends "base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

templates/blog/post/my_posts.html
{% extends 'base.html' %}
{% block title %}My Posts{% endblock %}
{% block content %}
<h2>My Posts</h2>
<a href="{% url 'blog:post_add' %}">+ Add New Post</a>
{% for post in posts %}
    <div>
        <h3>{{ post.title }}</h3>
        <p>{{ post.publish }}</p>
        <a href="{{ post.get_absolute_url }}">View</a> |
        <a href="{% url 'blog:post_edit' post.pk %}">Edit</a> |
        <a href="{% url 'blog:post_delete' post.pk %}">Delete</a>
    </div>
{% empty %}
    <p>You have no posts.</p>
{% endfor %}
{% endblock %}

templates/blog/post/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Post{% endblock %}
{% block content %}
<h2>Are you sure you want to delete "{{ object.title }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'blog:my_posts' %}">Cancel</a>
</form>
{% endblock %}

templates/blog/post/post_form.html
{% extends 'base_bootstrap.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ view.object|default:'Add' }} Post{% endblock %}
{% block content %}
<h2>{{ view.object|default:'Add' }} Post</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy}}
    <button type="submit">Save</button>
</form>
{% endblock %}

templates/blog/post/share.html
{% extends 'base.html' %}
{% block title %}
    Share a post
{% endblock %}
{% block content %}
    {% if sent %}
        <h1>Email successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="" method="post">
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}